import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: {
    resolve: true,
  },
  sourcemap: true,
  clean: true,
  target: 'es2020',
  minify: true,
  outDir: 'dist',
  tsconfig: './tsconfig.json',
  external: ['node:process'],
  noExternal: [],
  // Add this to handle CJS/ESM interop
  banner: {
    js: `// @ts-nocheck\n// @ts-ignore\n// This file is auto-generated by tsup`,
  },
  // Ensure proper exports for both ESM and CJS
  esbuildOptions(options) {
    options.banner = {
      js: `// @ts-nocheck\n// @ts-ignore`,
    };
  },
});
